# Generated by Django 5.2.9 on 2026-05-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_options_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog\\default.jpg', upload_to='blog/'),
        ),
    ]
